using Moq;
using WeatherMcpServer.AI;
using WeatherMcpServer.Domain;

namespace WeatherMcpServer.Tests
{
    public class AiSummaryServiceTests
    {
        [Fact]
        public async Task GenerateSummaryAsync_ReturnsSummaryFromAdapter()
        {
            var mockAdapter = new Mock<IAiAdapter>();
            var telemetry = new List<TelemetryData>
               {
                   new TelemetryData { Temperature = 25, Humidity = 50 },
                   new TelemetryData { Temperature = 30, Humidity = 60 },
               };

            var expectedSummary = "Summary generated by Claude";
            mockAdapter.Setup(a => a.GenerateSummaryAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
                       .ReturnsAsync(expectedSummary);

            var service = new AiSummaryService(new List<IAiAdapter> { mockAdapter.Object });

            var result = await service.GenerateSummaryAsync("station-1", telemetry, "Claude", CancellationToken.None);

            Assert.Equal(expectedSummary, result);
        }
    }
}
